import math, random, sys
random.seed(7)
P = "M0,0 C-30,-22 -96,-66 -116,-124 C-132,-170 -104,-210 -64,-214 C-46,-234 -14,-238 4,-224 C24,-240 62,-234 78,-210 C112,-204 136,-166 122,-120 C104,-64 32,-20 0,0 Z"
def veins():
    out=[]
    for a in (-46,-30,-15,0,15,30,46):
        r=math.radians(a); x=math.sin(r)*190; y=-math.cos(r)*190
        cx=math.sin(r)*90; cy=-math.cos(r)*100
        out.append(f'M0,-14 Q{cx:.0f},{cy:.0f} {x:.0f},{y:.0f}')
    return ' '.join(out)
V=veins()
def petals(pid):
    s=[]
    angles=[-8,64,136,208,280]
    for i,a in enumerate(angles):
        sc=[0.8,0.78,0.82,0.77,0.8][i]
        s.append(f'<g transform="rotate({a}) scale({sc})"><g class="hib-petal" style="--i:{i}"><path d="{P}" fill="url(#{pid}-pg)" stroke="#d9638a" stroke-opacity=".55" stroke-width="1.6"/><path d="{V}" fill="none" stroke="#fff" stroke-opacity=".38" stroke-width="1.3" stroke-linecap="round"/><path d="{P}" fill="url(#{pid}-ps)"/></g></g>')
    return ''.join(s)
LEAF="M0,0 C36,-34 120,-40 196,-4 C124,34 40,30 0,0 Z"
def leaves(pid):
    s=[]
    for i,(a,sc) in enumerate([(-118,.8),(-160,.7),(-48,.78),(-6,.66),(140,.78),(96,.7),(30,.62)]):
        s.append(f'<g transform="rotate({a}) translate(96,0) scale({sc})"><g class="hib-leaf" style="--i:{i}"><path d="{LEAF}" fill="url(#{pid}-lg)"/><path d="M6,0 C60,-6 120,-6 186,-4" fill="none" stroke="#f3e2b8" stroke-opacity=".7" stroke-width="1.4"/></g></g>')
    return ''.join(s)
def sprigs(pid):
    s=[]
    for i,(a) in enumerate([-82,182,64,-20]):
        s.append(f'<g transform="rotate({a}) translate(146,0)"><g class="hib-sprig" style="--i:{i}"><path d="M0,0 C30,-4 60,-14 82,-30 M40,-8 C52,-24 56,-36 58,-46 M58,-18 C74,-16 86,-10 96,-2" fill="none" stroke="#c9a35f" stroke-width="2" stroke-linecap="round"/><circle cx="84" cy="-32" r="6" fill="url(#{pid}-gold)"/><circle cx="58" cy="-48" r="5" fill="url(#{pid}-gold)"/><circle cx="98" cy="-1" r="5.5" fill="url(#{pid}-gold)"/></g></g>')
    return ''.join(s)
def stamen(pid):
    pol=[]
    for k in range(26):
        t=random.uniform(.6,.93)
        x=t*146+random.uniform(-13,13); y=-t*222+random.uniform(-11,11)
        pol.append(f'<circle class="hib-pollen" style="--j:{k%9}" cx="{x:.0f}" cy="{y:.0f}" r="{random.uniform(2.6,4.4):.1f}" fill="url(#{pid}-gold)"/>')
    stig=[]
    for k in range(5):
        a=math.radians(-60+k*30); x=156+math.cos(a)*16; y=-232+math.sin(a)*16-6
        stig.append(f'<path d="M150,-226 L{x:.0f},{y:.0f}" stroke="#b5174a" stroke-width="2.2" stroke-linecap="round"/><circle cx="{x:.0f}" cy="{y:.0f}" r="5.5" fill="#a8123f"/>')
    return f'<path class="hib-column" pathLength="100" d="M0,0 C30,-70 84,-150 150,-226" fill="none" stroke="url(#{pid}-cg)" stroke-width="7" stroke-linecap="round"/>' + ''.join(pol) + '<g class="hib-stigma">'+''.join(stig)+'</g>'
def defs(pid):
    return f'''<defs>
<radialGradient id="{pid}-pg" gradientUnits="userSpaceOnUse" cx="0" cy="0" r="236"><stop offset="0" stop-color="#8e0c35"/><stop offset=".16" stop-color="#bd2058"/><stop offset=".36" stop-color="#e8708f"/><stop offset=".66" stop-color="#f6a9bf"/><stop offset="1" stop-color="#fcd9e3"/></radialGradient>
<linearGradient id="{pid}-ps" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#fff" stop-opacity="0"/><stop offset=".55" stop-color="#fff" stop-opacity=".18"/><stop offset="1" stop-color="#7a0f2e" stop-opacity=".12"/></linearGradient>
<linearGradient id="{pid}-lg" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#7d7a3e"/><stop offset=".55" stop-color="#b39457"/><stop offset="1" stop-color="#dcc28a"/></linearGradient>
<linearGradient id="{pid}-cg" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stop-color="#b8204f"/><stop offset="1" stop-color="#f7c3d1"/></linearGradient>
<radialGradient id="{pid}-gold" cx=".35" cy=".35" r=".7"><stop offset="0" stop-color="#fff3cf"/><stop offset=".5" stop-color="#e2b866"/><stop offset="1" stop-color="#a87f3c"/></radialGradient>
<radialGradient id="{pid}-eye" cx="0" cy="0" r="60" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#5e0a24"/><stop offset=".5" stop-color="#8e0c35" stop-opacity=".7"/><stop offset="1" stop-color="#8e0c35" stop-opacity="0"/></radialGradient>
</defs>'''
def build(pid):
    vb='viewBox="-270 -270 540 540"'
    back=f'<svg class="hib-layer hib-back" {vb} aria-hidden="true">{defs(pid)}<circle class="hib-ring" r="252" pathLength="100" fill="none" stroke="#c9a35f" stroke-width="1.6"/>{leaves(pid)}{sprigs(pid)}</svg>'
    mid=f'<svg class="hib-layer hib-mid" {vb} aria-hidden="true">{petals(pid)}<circle class="hib-eye" r="60" fill="url(#{pid}-eye)"/></svg>'
    front=f'<svg class="hib-layer hib-front" {vb} aria-hidden="true">{stamen(pid)}</svg>'
    return back, mid, front
def emit_ts(path):
    b,m,f=build('__PID__')
    import json
    open(path,'w').write('// Generated by docs/tools/gen_hibiscus.py. Hand-drawn SVG hibiscus in three depth layers.\n'
      + 'export const back = ' + json.dumps(b) + ';\n'
      + 'export const mid = ' + json.dumps(m) + ';\n'
      + 'export const front = ' + json.dumps(f) + ';\n')
if __name__=='__main__':
    if len(sys.argv)>2 and sys.argv[2]=='ts':
        emit_ts(sys.argv[1]); raise SystemExit
    import sys
    b,m,f=build('h')
    open(sys.argv[1],'w').write(f'''<!doctype html><html><body style="margin:0;background:#fbf7f3"><div style="position:relative;width:540px;height:540px">
<style>.hib-layer{{position:absolute;inset:0;width:100%;height:100%}}</style>{b}{m}{f}</div></body></html>''')
